//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_acceso_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURASPJ
    {
        public FACTURASPJ()
        {
            this.CHEQUESPJs = new HashSet<CHEQUESPJ>();
        }
    
        public int NUMEROFACTURA { get; set; }
        public int CODIGOPROVEEDOR { get; set; }
        public Nullable<decimal> VALORFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAVENCIMIENTO { get; set; }
    
        public virtual ICollection<CHEQUESPJ> CHEQUESPJs { get; set; }
        public virtual PROVEEDORESPJ PROVEEDORESPJ { get; set; }
    }
}
