//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_acceso_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORESPJ
    {
        public PROVEEDORESPJ()
        {
            this.FACTURASPJs = new HashSet<FACTURASPJ>();
        }
    
        public int CODIGOPROVEEDOR { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual ICollection<FACTURASPJ> FACTURASPJs { get; set; }
    }
}
